pipeline:
  update_pr:
    image: plugins/git
    commands:
    - export BRANCH_SRC=origin/${DRONE_COMMIT_REFSPEC%%:*} BRANCH_DST=origin/${DRONE_BRANCH}
    - cp -rpf .git .git.bak
    - git config --global user.email "service@storiqa.com" && git config --global user.name "Storiqa Common"
    - git fetch && git checkout $BRANCH_SRC && git merge --no-commit $BRANCH_DST
    - rm -rf .git && mv -f .git.bak .git
    when:
      event: pull_request
  build:
    image: maven:3.5
    commands:
    - cd kafka-elastic-sink-connector && mvn clean package && cd ..
    - cd debezium && mvn clean package && cd ..
  package:
    image: plugins/docker
    repo: storiqateam/kafka-connect
    tags:
    - ${DRONE_BRANCH//\//_}
    - ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    username: stqcommon
    password: "Tz-q6qDL#d3Mz8hm"

